package io.github.miklires.mprotect.storage;

import io.github.miklires.mprotect.MProtectPlugin;
import io.github.miklires.mprotect.model.CheckType;
import io.github.miklires.mprotect.model.ViolationRecord;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public final class ViolationStore implements AutoCloseable {
    private final MProtectPlugin plugin;
    private final ExecutorService executor = Executors.newSingleThreadExecutor(Thread.ofPlatform().name("mprotect-storage").factory());
    private final String jdbcUrl;
    private final Path logFile;

    public ViolationStore(MProtectPlugin plugin) {
        this.plugin = plugin;
        String fileName = plugin.config().text("storage.file", "violations").replaceAll("[^A-Za-z0-9._-]", "_");
        Path base = plugin.getDataFolder().toPath().resolve("data");
        this.jdbcUrl = "jdbc:h2:file:" + base.resolve(fileName).toAbsolutePath().toString().replace('\\', '/');
        this.logFile = plugin.getDataFolder().toPath().resolve("violations.jsonl");
    }

    public CompletableFuture<Void> start() {
        return CompletableFuture.runAsync(() -> {
            try {
                Class.forName("org.h2.Driver", true, plugin.getClass().getClassLoader());
                Files.createDirectories(plugin.getDataFolder().toPath().resolve("data"));
                try (Connection connection = connection(); Statement statement = connection.createStatement()) {
                    statement.executeUpdate("CREATE TABLE IF NOT EXISTS mprotect_schema (version INTEGER PRIMARY KEY, applied_at BIGINT NOT NULL)");
                    statement.executeUpdate("CREATE TABLE IF NOT EXISTS violations (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, occurred_at BIGINT NOT NULL, player_uuid VARCHAR(36) NOT NULL, player_name VARCHAR(64) NOT NULL, check_type VARCHAR(32) NOT NULL, detail VARCHAR(1024) NOT NULL, world VARCHAR(128) NOT NULL, block_x INTEGER NOT NULL, block_y INTEGER NOT NULL, block_z INTEGER NOT NULL)");
                    statement.executeUpdate("CREATE INDEX IF NOT EXISTS idx_violations_time ON violations(occurred_at)");
                    statement.executeUpdate("CREATE INDEX IF NOT EXISTS idx_violations_player ON violations(player_name)");
                    try (PreparedStatement insert = connection.prepareStatement("MERGE INTO mprotect_schema KEY(version) VALUES(1, ?)") ) {
                        insert.setLong(1, System.currentTimeMillis());
                        insert.executeUpdate();
                    }
                }
                cleanup();
            } catch (SQLException | IOException | ClassNotFoundException exception) {
                throw new IllegalStateException("Could not initialize violation storage", exception);
            }
        }, executor);
    }

    public void save(ViolationRecord record) {
        executor.execute(() -> {
            try (Connection connection = connection(); PreparedStatement statement = connection.prepareStatement(
                    "INSERT INTO violations(occurred_at, player_uuid, player_name, check_type, detail, world, block_x, block_y, block_z) VALUES(?,?,?,?,?,?,?,?,?)")) {
                statement.setLong(1, record.occurredAt().toEpochMilli());
                statement.setString(2, record.playerId().toString());
                statement.setString(3, record.playerName());
                statement.setString(4, record.check().name());
                statement.setString(5, record.detail());
                statement.setString(6, record.world());
                statement.setInt(7, record.blockX());
                statement.setInt(8, record.blockY());
                statement.setInt(9, record.blockZ());
                statement.executeUpdate();
                if (plugin.config().bool("alerts.file-log", true)) append(record);
            } catch (SQLException | IOException exception) {
                plugin.getLogger().warning("Could not store violation: " + exception.getMessage());
            }
        });
    }

    public CompletableFuture<List<ViolationRecord>> recent(String playerName, int limit) {
        return CompletableFuture.supplyAsync(() -> {
            List<ViolationRecord> records = new ArrayList<>();
            String sql = playerName == null
                    ? "SELECT * FROM violations ORDER BY occurred_at DESC LIMIT ?"
                    : "SELECT * FROM violations WHERE LOWER(player_name)=LOWER(?) ORDER BY occurred_at DESC LIMIT ?";
            try (Connection connection = connection(); PreparedStatement statement = connection.prepareStatement(sql)) {
                int parameter = 1;
                if (playerName != null) statement.setString(parameter++, playerName);
                statement.setInt(parameter, limit);
                try (ResultSet result = statement.executeQuery()) {
                    while (result.next()) records.add(read(result));
                }
            } catch (SQLException exception) {
                plugin.getLogger().warning("Could not query violations: " + exception.getMessage());
            }
            return records;
        }, executor);
    }

    private void cleanup() throws SQLException, IOException {
        long cutoff = Instant.now().minus(plugin.config().integer("storage.retention-days", 30), ChronoUnit.DAYS).toEpochMilli();
        try (Connection connection = connection(); PreparedStatement statement = connection.prepareStatement("DELETE FROM violations WHERE occurred_at < ?")) {
            statement.setLong(1, cutoff);
            statement.executeUpdate();
        }
        if (Files.exists(logFile) && Files.size(logFile) > 32L * 1024L * 1024L) {
            Files.move(logFile, logFile.resolveSibling("violations.previous.jsonl"), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
        }
    }

    private ViolationRecord read(ResultSet result) throws SQLException {
        return new ViolationRecord(
                result.getLong("id"), Instant.ofEpochMilli(result.getLong("occurred_at")),
                UUID.fromString(result.getString("player_uuid")), result.getString("player_name"),
                CheckType.valueOf(result.getString("check_type")), result.getString("detail"), result.getString("world"),
                result.getInt("block_x"), result.getInt("block_y"), result.getInt("block_z"));
    }

    private Connection connection() throws SQLException {
        return DriverManager.getConnection(jdbcUrl);
    }

    private void append(ViolationRecord record) throws IOException {
        String json = "{\"time\":" + record.occurredAt().toEpochMilli()
                + ",\"player_uuid\":\"" + record.playerId() + "\",\"player_name\":\"" + escape(record.playerName())
                + "\",\"check\":\"" + record.check().key() + "\",\"detail\":\"" + escape(record.detail())
                + "\",\"world\":\"" + escape(record.world()) + "\",\"x\":" + record.blockX()
                + ",\"y\":" + record.blockY() + ",\"z\":" + record.blockZ() + "}" + System.lineSeparator();
        Files.writeString(logFile, json, StandardCharsets.UTF_8, StandardOpenOption.CREATE, StandardOpenOption.APPEND);
    }

    private String escape(String value) {
        return value.replace("\\", "\\\\").replace("\"", "\\\"").replace("\r", "\\r").replace("\n", "\\n");
    }

    @Override
    public void close() {
        executor.shutdown();
    }
}
